VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.define "vagrant" do |vagrant|
    vagrant.vm.box = "ubuntu/jammy64"
    vagrant.vm.network "forwarded_port", guest: 8080, host: 8080
  end
end